// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package iso_pb

import (
	driver "database/sql/driver"
	fmt "fmt"
)

// Country
const (
	Country_UNSPECIFIED Country = 0
	Country_AD          Country = 1
	Country_AE          Country = 2
	Country_AF          Country = 3
	Country_AG          Country = 4
	Country_AI          Country = 5
	Country_AL          Country = 6
	Country_AM          Country = 7
	Country_AN          Country = 8
	Country_AO          Country = 9
	Country_AQ          Country = 10
	Country_AR          Country = 11
	Country_AS          Country = 12
	Country_AT          Country = 13
	Country_AU          Country = 14
	Country_AW          Country = 15
	Country_AZ          Country = 16
	Country_BA          Country = 17
	Country_BB          Country = 18
	Country_BD          Country = 19
	Country_BE          Country = 20
	Country_BF          Country = 21
	Country_BG          Country = 22
	Country_BH          Country = 23
	Country_BI          Country = 24
	Country_BJ          Country = 25
	Country_BM          Country = 26
	Country_BN          Country = 27
	Country_BO          Country = 28
	Country_BR          Country = 29
	Country_BS          Country = 30
	Country_BT          Country = 31
	Country_BV          Country = 32
	Country_BW          Country = 33
	Country_BY          Country = 34
	Country_BZ          Country = 35
	Country_CA          Country = 36
	Country_CC          Country = 37
	Country_CF          Country = 38
	Country_CG          Country = 39
	Country_CH          Country = 40
	Country_CI          Country = 41
	Country_CK          Country = 42
	Country_CL          Country = 43
	Country_CM          Country = 44
	Country_CN          Country = 45
	Country_CO          Country = 46
	Country_CR          Country = 47
	Country_CS          Country = 48
	Country_CU          Country = 49
	Country_CV          Country = 50
	Country_CX          Country = 51
	Country_CY          Country = 52
	Country_CZ          Country = 53
	Country_DE          Country = 54
	Country_DJ          Country = 55
	Country_DK          Country = 56
	Country_DM          Country = 57
	Country_DO          Country = 58
	Country_DZ          Country = 59
	Country_EC          Country = 60
	Country_EE          Country = 61
	Country_EG          Country = 62
	Country_EH          Country = 63
	Country_ER          Country = 64
	Country_ES          Country = 65
	Country_ET          Country = 66
	Country_FI          Country = 67
	Country_FJ          Country = 68
	Country_FK          Country = 69
	Country_FM          Country = 70
	Country_FO          Country = 71
	Country_FR          Country = 72
	Country_FX          Country = 73
	Country_GA          Country = 74
	Country_GB          Country = 75
	Country_GD          Country = 76
	Country_GE          Country = 77
	Country_GF          Country = 78
	Country_GH          Country = 79
	Country_GI          Country = 80
	Country_GL          Country = 81
	Country_GM          Country = 82
	Country_GN          Country = 83
	Country_GP          Country = 84
	Country_GQ          Country = 85
	Country_GR          Country = 86
	Country_GS          Country = 87
	Country_GT          Country = 88
	Country_GU          Country = 89
	Country_GW          Country = 90
	Country_GY          Country = 91
	Country_HK          Country = 92
	Country_HM          Country = 93
	Country_HN          Country = 94
	Country_HR          Country = 95
	Country_HT          Country = 96
	Country_HU          Country = 97
	Country_ID          Country = 98
	Country_IE          Country = 99
	Country_IL          Country = 100
	Country_IN          Country = 101
	Country_IO          Country = 102
	Country_IQ          Country = 103
	Country_IR          Country = 104
	Country_IS          Country = 105
	Country_IT          Country = 106
	Country_JM          Country = 107
	Country_JO          Country = 108
	Country_JP          Country = 109
	Country_KE          Country = 110
	Country_KG          Country = 111
	Country_KH          Country = 112
	Country_KI          Country = 113
	Country_KM          Country = 114
	Country_KN          Country = 115
	Country_KP          Country = 116
	Country_KR          Country = 117
	Country_KW          Country = 118
	Country_KY          Country = 119
	Country_KZ          Country = 120
	Country_LA          Country = 121
	Country_LB          Country = 122
	Country_LC          Country = 123
	Country_LI          Country = 124
	Country_LK          Country = 125
	Country_LR          Country = 126
	Country_LS          Country = 127
	Country_LT          Country = 128
	Country_LU          Country = 129
	Country_LV          Country = 130
	Country_LY          Country = 131
	Country_MA          Country = 132
	Country_MC          Country = 133
	Country_MD          Country = 134
	Country_MG          Country = 135
	Country_MH          Country = 136
	Country_MK          Country = 137
	Country_ML          Country = 138
	Country_MM          Country = 139
	Country_MN          Country = 140
	Country_MO          Country = 141
	Country_MP          Country = 142
	Country_MQ          Country = 143
	Country_MR          Country = 144
	Country_MS          Country = 145
	Country_MT          Country = 146
	Country_MU          Country = 147
	Country_MV          Country = 148
	Country_MW          Country = 149
	Country_MX          Country = 150
	Country_MY          Country = 151
	Country_MZ          Country = 152
	Country_NA          Country = 153
	Country_NC          Country = 154
	Country_NE          Country = 155
	Country_NF          Country = 156
	Country_NG          Country = 157
	Country_NI          Country = 158
	Country_NL          Country = 159
	Country_NO          Country = 160
	Country_NP          Country = 161
	Country_NR          Country = 162
	Country_NU          Country = 163
	Country_NZ          Country = 164
	Country_OM          Country = 165
	Country_PA          Country = 166
	Country_PE          Country = 167
	Country_PF          Country = 168
	Country_PG          Country = 169
	Country_PH          Country = 170
	Country_PK          Country = 171
	Country_PL          Country = 172
	Country_PM          Country = 173
	Country_PN          Country = 174
	Country_PR          Country = 175
	Country_PT          Country = 176
	Country_PW          Country = 177
	Country_PY          Country = 178
	Country_QA          Country = 179
	Country_RE          Country = 180
	Country_RO          Country = 181
	Country_RU          Country = 182
	Country_RW          Country = 183
	Country_SA          Country = 184
	Country_SB          Country = 185
	Country_SC          Country = 186
	Country_SD          Country = 187
	Country_SE          Country = 188
	Country_SG          Country = 189
	Country_SH          Country = 190
	Country_SI          Country = 191
	Country_SJ          Country = 192
	Country_SK          Country = 193
	Country_SL          Country = 194
	Country_SM          Country = 195
	Country_SN          Country = 196
	Country_SO          Country = 197
	Country_SR          Country = 198
	Country_ST          Country = 199
	Country_SU          Country = 200
	Country_SV          Country = 201
	Country_SY          Country = 202
	Country_SZ          Country = 203
	Country_TC          Country = 204
	Country_TD          Country = 205
	Country_TF          Country = 206
	Country_TG          Country = 207
	Country_TH          Country = 208
	Country_TJ          Country = 209
	Country_TK          Country = 210
	Country_TM          Country = 211
	Country_TN          Country = 212
	Country_TO          Country = 213
	Country_TP          Country = 214
	Country_TR          Country = 215
	Country_TT          Country = 216
	Country_TV          Country = 217
	Country_TW          Country = 218
	Country_TZ          Country = 219
	Country_UA          Country = 220
	Country_UG          Country = 221
	Country_UK          Country = 222
	Country_UM          Country = 223
	Country_US          Country = 224
	Country_UY          Country = 225
	Country_UZ          Country = 226
	Country_VA          Country = 227
	Country_VC          Country = 228
	Country_VE          Country = 229
	Country_VG          Country = 230
	Country_VI          Country = 231
	Country_VN          Country = 232
	Country_VU          Country = 233
	Country_WF          Country = 234
	Country_WS          Country = 235
	Country_YE          Country = 236
	Country_YT          Country = 237
	Country_YU          Country = 238
	Country_ZA          Country = 239
	Country_ZM          Country = 240
	Country_ZR          Country = 241
	Country_ZW          Country = 242
)

var (
	Country_name_short = map[int32]string{
		0:   "UNSPECIFIED",
		1:   "AD",
		2:   "AE",
		3:   "AF",
		4:   "AG",
		5:   "AI",
		6:   "AL",
		7:   "AM",
		8:   "AN",
		9:   "AO",
		10:  "AQ",
		11:  "AR",
		12:  "AS",
		13:  "AT",
		14:  "AU",
		15:  "AW",
		16:  "AZ",
		17:  "BA",
		18:  "BB",
		19:  "BD",
		20:  "BE",
		21:  "BF",
		22:  "BG",
		23:  "BH",
		24:  "BI",
		25:  "BJ",
		26:  "BM",
		27:  "BN",
		28:  "BO",
		29:  "BR",
		30:  "BS",
		31:  "BT",
		32:  "BV",
		33:  "BW",
		34:  "BY",
		35:  "BZ",
		36:  "CA",
		37:  "CC",
		38:  "CF",
		39:  "CG",
		40:  "CH",
		41:  "CI",
		42:  "CK",
		43:  "CL",
		44:  "CM",
		45:  "CN",
		46:  "CO",
		47:  "CR",
		48:  "CS",
		49:  "CU",
		50:  "CV",
		51:  "CX",
		52:  "CY",
		53:  "CZ",
		54:  "DE",
		55:  "DJ",
		56:  "DK",
		57:  "DM",
		58:  "DO",
		59:  "DZ",
		60:  "EC",
		61:  "EE",
		62:  "EG",
		63:  "EH",
		64:  "ER",
		65:  "ES",
		66:  "ET",
		67:  "FI",
		68:  "FJ",
		69:  "FK",
		70:  "FM",
		71:  "FO",
		72:  "FR",
		73:  "FX",
		74:  "GA",
		75:  "GB",
		76:  "GD",
		77:  "GE",
		78:  "GF",
		79:  "GH",
		80:  "GI",
		81:  "GL",
		82:  "GM",
		83:  "GN",
		84:  "GP",
		85:  "GQ",
		86:  "GR",
		87:  "GS",
		88:  "GT",
		89:  "GU",
		90:  "GW",
		91:  "GY",
		92:  "HK",
		93:  "HM",
		94:  "HN",
		95:  "HR",
		96:  "HT",
		97:  "HU",
		98:  "ID",
		99:  "IE",
		100: "IL",
		101: "IN",
		102: "IO",
		103: "IQ",
		104: "IR",
		105: "IS",
		106: "IT",
		107: "JM",
		108: "JO",
		109: "JP",
		110: "KE",
		111: "KG",
		112: "KH",
		113: "KI",
		114: "KM",
		115: "KN",
		116: "KP",
		117: "KR",
		118: "KW",
		119: "KY",
		120: "KZ",
		121: "LA",
		122: "LB",
		123: "LC",
		124: "LI",
		125: "LK",
		126: "LR",
		127: "LS",
		128: "LT",
		129: "LU",
		130: "LV",
		131: "LY",
		132: "MA",
		133: "MC",
		134: "MD",
		135: "MG",
		136: "MH",
		137: "MK",
		138: "ML",
		139: "MM",
		140: "MN",
		141: "MO",
		142: "MP",
		143: "MQ",
		144: "MR",
		145: "MS",
		146: "MT",
		147: "MU",
		148: "MV",
		149: "MW",
		150: "MX",
		151: "MY",
		152: "MZ",
		153: "NA",
		154: "NC",
		155: "NE",
		156: "NF",
		157: "NG",
		158: "NI",
		159: "NL",
		160: "NO",
		161: "NP",
		162: "NR",
		163: "NU",
		164: "NZ",
		165: "OM",
		166: "PA",
		167: "PE",
		168: "PF",
		169: "PG",
		170: "PH",
		171: "PK",
		172: "PL",
		173: "PM",
		174: "PN",
		175: "PR",
		176: "PT",
		177: "PW",
		178: "PY",
		179: "QA",
		180: "RE",
		181: "RO",
		182: "RU",
		183: "RW",
		184: "SA",
		185: "SB",
		186: "SC",
		187: "SD",
		188: "SE",
		189: "SG",
		190: "SH",
		191: "SI",
		192: "SJ",
		193: "SK",
		194: "SL",
		195: "SM",
		196: "SN",
		197: "SO",
		198: "SR",
		199: "ST",
		200: "SU",
		201: "SV",
		202: "SY",
		203: "SZ",
		204: "TC",
		205: "TD",
		206: "TF",
		207: "TG",
		208: "TH",
		209: "TJ",
		210: "TK",
		211: "TM",
		212: "TN",
		213: "TO",
		214: "TP",
		215: "TR",
		216: "TT",
		217: "TV",
		218: "TW",
		219: "TZ",
		220: "UA",
		221: "UG",
		222: "UK",
		223: "UM",
		224: "US",
		225: "UY",
		226: "UZ",
		227: "VA",
		228: "VC",
		229: "VE",
		230: "VG",
		231: "VI",
		232: "VN",
		233: "VU",
		234: "WF",
		235: "WS",
		236: "YE",
		237: "YT",
		238: "YU",
		239: "ZA",
		240: "ZM",
		241: "ZR",
		242: "ZW",
	}
	Country_value_short = map[string]int32{
		"UNSPECIFIED": 0,
		"AD":          1,
		"AE":          2,
		"AF":          3,
		"AG":          4,
		"AI":          5,
		"AL":          6,
		"AM":          7,
		"AN":          8,
		"AO":          9,
		"AQ":          10,
		"AR":          11,
		"AS":          12,
		"AT":          13,
		"AU":          14,
		"AW":          15,
		"AZ":          16,
		"BA":          17,
		"BB":          18,
		"BD":          19,
		"BE":          20,
		"BF":          21,
		"BG":          22,
		"BH":          23,
		"BI":          24,
		"BJ":          25,
		"BM":          26,
		"BN":          27,
		"BO":          28,
		"BR":          29,
		"BS":          30,
		"BT":          31,
		"BV":          32,
		"BW":          33,
		"BY":          34,
		"BZ":          35,
		"CA":          36,
		"CC":          37,
		"CF":          38,
		"CG":          39,
		"CH":          40,
		"CI":          41,
		"CK":          42,
		"CL":          43,
		"CM":          44,
		"CN":          45,
		"CO":          46,
		"CR":          47,
		"CS":          48,
		"CU":          49,
		"CV":          50,
		"CX":          51,
		"CY":          52,
		"CZ":          53,
		"DE":          54,
		"DJ":          55,
		"DK":          56,
		"DM":          57,
		"DO":          58,
		"DZ":          59,
		"EC":          60,
		"EE":          61,
		"EG":          62,
		"EH":          63,
		"ER":          64,
		"ES":          65,
		"ET":          66,
		"FI":          67,
		"FJ":          68,
		"FK":          69,
		"FM":          70,
		"FO":          71,
		"FR":          72,
		"FX":          73,
		"GA":          74,
		"GB":          75,
		"GD":          76,
		"GE":          77,
		"GF":          78,
		"GH":          79,
		"GI":          80,
		"GL":          81,
		"GM":          82,
		"GN":          83,
		"GP":          84,
		"GQ":          85,
		"GR":          86,
		"GS":          87,
		"GT":          88,
		"GU":          89,
		"GW":          90,
		"GY":          91,
		"HK":          92,
		"HM":          93,
		"HN":          94,
		"HR":          95,
		"HT":          96,
		"HU":          97,
		"ID":          98,
		"IE":          99,
		"IL":          100,
		"IN":          101,
		"IO":          102,
		"IQ":          103,
		"IR":          104,
		"IS":          105,
		"IT":          106,
		"JM":          107,
		"JO":          108,
		"JP":          109,
		"KE":          110,
		"KG":          111,
		"KH":          112,
		"KI":          113,
		"KM":          114,
		"KN":          115,
		"KP":          116,
		"KR":          117,
		"KW":          118,
		"KY":          119,
		"KZ":          120,
		"LA":          121,
		"LB":          122,
		"LC":          123,
		"LI":          124,
		"LK":          125,
		"LR":          126,
		"LS":          127,
		"LT":          128,
		"LU":          129,
		"LV":          130,
		"LY":          131,
		"MA":          132,
		"MC":          133,
		"MD":          134,
		"MG":          135,
		"MH":          136,
		"MK":          137,
		"ML":          138,
		"MM":          139,
		"MN":          140,
		"MO":          141,
		"MP":          142,
		"MQ":          143,
		"MR":          144,
		"MS":          145,
		"MT":          146,
		"MU":          147,
		"MV":          148,
		"MW":          149,
		"MX":          150,
		"MY":          151,
		"MZ":          152,
		"NA":          153,
		"NC":          154,
		"NE":          155,
		"NF":          156,
		"NG":          157,
		"NI":          158,
		"NL":          159,
		"NO":          160,
		"NP":          161,
		"NR":          162,
		"NU":          163,
		"NZ":          164,
		"OM":          165,
		"PA":          166,
		"PE":          167,
		"PF":          168,
		"PG":          169,
		"PH":          170,
		"PK":          171,
		"PL":          172,
		"PM":          173,
		"PN":          174,
		"PR":          175,
		"PT":          176,
		"PW":          177,
		"PY":          178,
		"QA":          179,
		"RE":          180,
		"RO":          181,
		"RU":          182,
		"RW":          183,
		"SA":          184,
		"SB":          185,
		"SC":          186,
		"SD":          187,
		"SE":          188,
		"SG":          189,
		"SH":          190,
		"SI":          191,
		"SJ":          192,
		"SK":          193,
		"SL":          194,
		"SM":          195,
		"SN":          196,
		"SO":          197,
		"SR":          198,
		"ST":          199,
		"SU":          200,
		"SV":          201,
		"SY":          202,
		"SZ":          203,
		"TC":          204,
		"TD":          205,
		"TF":          206,
		"TG":          207,
		"TH":          208,
		"TJ":          209,
		"TK":          210,
		"TM":          211,
		"TN":          212,
		"TO":          213,
		"TP":          214,
		"TR":          215,
		"TT":          216,
		"TV":          217,
		"TW":          218,
		"TZ":          219,
		"UA":          220,
		"UG":          221,
		"UK":          222,
		"UM":          223,
		"US":          224,
		"UY":          225,
		"UZ":          226,
		"VA":          227,
		"VC":          228,
		"VE":          229,
		"VG":          230,
		"VI":          231,
		"VN":          232,
		"VU":          233,
		"WF":          234,
		"WS":          235,
		"YE":          236,
		"YT":          237,
		"YU":          238,
		"ZA":          239,
		"ZM":          240,
		"ZR":          241,
		"ZW":          242,
	}
	Country_value_either = map[string]int32{
		"UNSPECIFIED":         0,
		"COUNTRY_UNSPECIFIED": 0,
		"AD":                  1,
		"COUNTRY_AD":          1,
		"AE":                  2,
		"COUNTRY_AE":          2,
		"AF":                  3,
		"COUNTRY_AF":          3,
		"AG":                  4,
		"COUNTRY_AG":          4,
		"AI":                  5,
		"COUNTRY_AI":          5,
		"AL":                  6,
		"COUNTRY_AL":          6,
		"AM":                  7,
		"COUNTRY_AM":          7,
		"AN":                  8,
		"COUNTRY_AN":          8,
		"AO":                  9,
		"COUNTRY_AO":          9,
		"AQ":                  10,
		"COUNTRY_AQ":          10,
		"AR":                  11,
		"COUNTRY_AR":          11,
		"AS":                  12,
		"COUNTRY_AS":          12,
		"AT":                  13,
		"COUNTRY_AT":          13,
		"AU":                  14,
		"COUNTRY_AU":          14,
		"AW":                  15,
		"COUNTRY_AW":          15,
		"AZ":                  16,
		"COUNTRY_AZ":          16,
		"BA":                  17,
		"COUNTRY_BA":          17,
		"BB":                  18,
		"COUNTRY_BB":          18,
		"BD":                  19,
		"COUNTRY_BD":          19,
		"BE":                  20,
		"COUNTRY_BE":          20,
		"BF":                  21,
		"COUNTRY_BF":          21,
		"BG":                  22,
		"COUNTRY_BG":          22,
		"BH":                  23,
		"COUNTRY_BH":          23,
		"BI":                  24,
		"COUNTRY_BI":          24,
		"BJ":                  25,
		"COUNTRY_BJ":          25,
		"BM":                  26,
		"COUNTRY_BM":          26,
		"BN":                  27,
		"COUNTRY_BN":          27,
		"BO":                  28,
		"COUNTRY_BO":          28,
		"BR":                  29,
		"COUNTRY_BR":          29,
		"BS":                  30,
		"COUNTRY_BS":          30,
		"BT":                  31,
		"COUNTRY_BT":          31,
		"BV":                  32,
		"COUNTRY_BV":          32,
		"BW":                  33,
		"COUNTRY_BW":          33,
		"BY":                  34,
		"COUNTRY_BY":          34,
		"BZ":                  35,
		"COUNTRY_BZ":          35,
		"CA":                  36,
		"COUNTRY_CA":          36,
		"CC":                  37,
		"COUNTRY_CC":          37,
		"CF":                  38,
		"COUNTRY_CF":          38,
		"CG":                  39,
		"COUNTRY_CG":          39,
		"CH":                  40,
		"COUNTRY_CH":          40,
		"CI":                  41,
		"COUNTRY_CI":          41,
		"CK":                  42,
		"COUNTRY_CK":          42,
		"CL":                  43,
		"COUNTRY_CL":          43,
		"CM":                  44,
		"COUNTRY_CM":          44,
		"CN":                  45,
		"COUNTRY_CN":          45,
		"CO":                  46,
		"COUNTRY_CO":          46,
		"CR":                  47,
		"COUNTRY_CR":          47,
		"CS":                  48,
		"COUNTRY_CS":          48,
		"CU":                  49,
		"COUNTRY_CU":          49,
		"CV":                  50,
		"COUNTRY_CV":          50,
		"CX":                  51,
		"COUNTRY_CX":          51,
		"CY":                  52,
		"COUNTRY_CY":          52,
		"CZ":                  53,
		"COUNTRY_CZ":          53,
		"DE":                  54,
		"COUNTRY_DE":          54,
		"DJ":                  55,
		"COUNTRY_DJ":          55,
		"DK":                  56,
		"COUNTRY_DK":          56,
		"DM":                  57,
		"COUNTRY_DM":          57,
		"DO":                  58,
		"COUNTRY_DO":          58,
		"DZ":                  59,
		"COUNTRY_DZ":          59,
		"EC":                  60,
		"COUNTRY_EC":          60,
		"EE":                  61,
		"COUNTRY_EE":          61,
		"EG":                  62,
		"COUNTRY_EG":          62,
		"EH":                  63,
		"COUNTRY_EH":          63,
		"ER":                  64,
		"COUNTRY_ER":          64,
		"ES":                  65,
		"COUNTRY_ES":          65,
		"ET":                  66,
		"COUNTRY_ET":          66,
		"FI":                  67,
		"COUNTRY_FI":          67,
		"FJ":                  68,
		"COUNTRY_FJ":          68,
		"FK":                  69,
		"COUNTRY_FK":          69,
		"FM":                  70,
		"COUNTRY_FM":          70,
		"FO":                  71,
		"COUNTRY_FO":          71,
		"FR":                  72,
		"COUNTRY_FR":          72,
		"FX":                  73,
		"COUNTRY_FX":          73,
		"GA":                  74,
		"COUNTRY_GA":          74,
		"GB":                  75,
		"COUNTRY_GB":          75,
		"GD":                  76,
		"COUNTRY_GD":          76,
		"GE":                  77,
		"COUNTRY_GE":          77,
		"GF":                  78,
		"COUNTRY_GF":          78,
		"GH":                  79,
		"COUNTRY_GH":          79,
		"GI":                  80,
		"COUNTRY_GI":          80,
		"GL":                  81,
		"COUNTRY_GL":          81,
		"GM":                  82,
		"COUNTRY_GM":          82,
		"GN":                  83,
		"COUNTRY_GN":          83,
		"GP":                  84,
		"COUNTRY_GP":          84,
		"GQ":                  85,
		"COUNTRY_GQ":          85,
		"GR":                  86,
		"COUNTRY_GR":          86,
		"GS":                  87,
		"COUNTRY_GS":          87,
		"GT":                  88,
		"COUNTRY_GT":          88,
		"GU":                  89,
		"COUNTRY_GU":          89,
		"GW":                  90,
		"COUNTRY_GW":          90,
		"GY":                  91,
		"COUNTRY_GY":          91,
		"HK":                  92,
		"COUNTRY_HK":          92,
		"HM":                  93,
		"COUNTRY_HM":          93,
		"HN":                  94,
		"COUNTRY_HN":          94,
		"HR":                  95,
		"COUNTRY_HR":          95,
		"HT":                  96,
		"COUNTRY_HT":          96,
		"HU":                  97,
		"COUNTRY_HU":          97,
		"ID":                  98,
		"COUNTRY_ID":          98,
		"IE":                  99,
		"COUNTRY_IE":          99,
		"IL":                  100,
		"COUNTRY_IL":          100,
		"IN":                  101,
		"COUNTRY_IN":          101,
		"IO":                  102,
		"COUNTRY_IO":          102,
		"IQ":                  103,
		"COUNTRY_IQ":          103,
		"IR":                  104,
		"COUNTRY_IR":          104,
		"IS":                  105,
		"COUNTRY_IS":          105,
		"IT":                  106,
		"COUNTRY_IT":          106,
		"JM":                  107,
		"COUNTRY_JM":          107,
		"JO":                  108,
		"COUNTRY_JO":          108,
		"JP":                  109,
		"COUNTRY_JP":          109,
		"KE":                  110,
		"COUNTRY_KE":          110,
		"KG":                  111,
		"COUNTRY_KG":          111,
		"KH":                  112,
		"COUNTRY_KH":          112,
		"KI":                  113,
		"COUNTRY_KI":          113,
		"KM":                  114,
		"COUNTRY_KM":          114,
		"KN":                  115,
		"COUNTRY_KN":          115,
		"KP":                  116,
		"COUNTRY_KP":          116,
		"KR":                  117,
		"COUNTRY_KR":          117,
		"KW":                  118,
		"COUNTRY_KW":          118,
		"KY":                  119,
		"COUNTRY_KY":          119,
		"KZ":                  120,
		"COUNTRY_KZ":          120,
		"LA":                  121,
		"COUNTRY_LA":          121,
		"LB":                  122,
		"COUNTRY_LB":          122,
		"LC":                  123,
		"COUNTRY_LC":          123,
		"LI":                  124,
		"COUNTRY_LI":          124,
		"LK":                  125,
		"COUNTRY_LK":          125,
		"LR":                  126,
		"COUNTRY_LR":          126,
		"LS":                  127,
		"COUNTRY_LS":          127,
		"LT":                  128,
		"COUNTRY_LT":          128,
		"LU":                  129,
		"COUNTRY_LU":          129,
		"LV":                  130,
		"COUNTRY_LV":          130,
		"LY":                  131,
		"COUNTRY_LY":          131,
		"MA":                  132,
		"COUNTRY_MA":          132,
		"MC":                  133,
		"COUNTRY_MC":          133,
		"MD":                  134,
		"COUNTRY_MD":          134,
		"MG":                  135,
		"COUNTRY_MG":          135,
		"MH":                  136,
		"COUNTRY_MH":          136,
		"MK":                  137,
		"COUNTRY_MK":          137,
		"ML":                  138,
		"COUNTRY_ML":          138,
		"MM":                  139,
		"COUNTRY_MM":          139,
		"MN":                  140,
		"COUNTRY_MN":          140,
		"MO":                  141,
		"COUNTRY_MO":          141,
		"MP":                  142,
		"COUNTRY_MP":          142,
		"MQ":                  143,
		"COUNTRY_MQ":          143,
		"MR":                  144,
		"COUNTRY_MR":          144,
		"MS":                  145,
		"COUNTRY_MS":          145,
		"MT":                  146,
		"COUNTRY_MT":          146,
		"MU":                  147,
		"COUNTRY_MU":          147,
		"MV":                  148,
		"COUNTRY_MV":          148,
		"MW":                  149,
		"COUNTRY_MW":          149,
		"MX":                  150,
		"COUNTRY_MX":          150,
		"MY":                  151,
		"COUNTRY_MY":          151,
		"MZ":                  152,
		"COUNTRY_MZ":          152,
		"NA":                  153,
		"COUNTRY_NA":          153,
		"NC":                  154,
		"COUNTRY_NC":          154,
		"NE":                  155,
		"COUNTRY_NE":          155,
		"NF":                  156,
		"COUNTRY_NF":          156,
		"NG":                  157,
		"COUNTRY_NG":          157,
		"NI":                  158,
		"COUNTRY_NI":          158,
		"NL":                  159,
		"COUNTRY_NL":          159,
		"NO":                  160,
		"COUNTRY_NO":          160,
		"NP":                  161,
		"COUNTRY_NP":          161,
		"NR":                  162,
		"COUNTRY_NR":          162,
		"NU":                  163,
		"COUNTRY_NU":          163,
		"NZ":                  164,
		"COUNTRY_NZ":          164,
		"OM":                  165,
		"COUNTRY_OM":          165,
		"PA":                  166,
		"COUNTRY_PA":          166,
		"PE":                  167,
		"COUNTRY_PE":          167,
		"PF":                  168,
		"COUNTRY_PF":          168,
		"PG":                  169,
		"COUNTRY_PG":          169,
		"PH":                  170,
		"COUNTRY_PH":          170,
		"PK":                  171,
		"COUNTRY_PK":          171,
		"PL":                  172,
		"COUNTRY_PL":          172,
		"PM":                  173,
		"COUNTRY_PM":          173,
		"PN":                  174,
		"COUNTRY_PN":          174,
		"PR":                  175,
		"COUNTRY_PR":          175,
		"PT":                  176,
		"COUNTRY_PT":          176,
		"PW":                  177,
		"COUNTRY_PW":          177,
		"PY":                  178,
		"COUNTRY_PY":          178,
		"QA":                  179,
		"COUNTRY_QA":          179,
		"RE":                  180,
		"COUNTRY_RE":          180,
		"RO":                  181,
		"COUNTRY_RO":          181,
		"RU":                  182,
		"COUNTRY_RU":          182,
		"RW":                  183,
		"COUNTRY_RW":          183,
		"SA":                  184,
		"COUNTRY_SA":          184,
		"SB":                  185,
		"COUNTRY_SB":          185,
		"SC":                  186,
		"COUNTRY_SC":          186,
		"SD":                  187,
		"COUNTRY_SD":          187,
		"SE":                  188,
		"COUNTRY_SE":          188,
		"SG":                  189,
		"COUNTRY_SG":          189,
		"SH":                  190,
		"COUNTRY_SH":          190,
		"SI":                  191,
		"COUNTRY_SI":          191,
		"SJ":                  192,
		"COUNTRY_SJ":          192,
		"SK":                  193,
		"COUNTRY_SK":          193,
		"SL":                  194,
		"COUNTRY_SL":          194,
		"SM":                  195,
		"COUNTRY_SM":          195,
		"SN":                  196,
		"COUNTRY_SN":          196,
		"SO":                  197,
		"COUNTRY_SO":          197,
		"SR":                  198,
		"COUNTRY_SR":          198,
		"ST":                  199,
		"COUNTRY_ST":          199,
		"SU":                  200,
		"COUNTRY_SU":          200,
		"SV":                  201,
		"COUNTRY_SV":          201,
		"SY":                  202,
		"COUNTRY_SY":          202,
		"SZ":                  203,
		"COUNTRY_SZ":          203,
		"TC":                  204,
		"COUNTRY_TC":          204,
		"TD":                  205,
		"COUNTRY_TD":          205,
		"TF":                  206,
		"COUNTRY_TF":          206,
		"TG":                  207,
		"COUNTRY_TG":          207,
		"TH":                  208,
		"COUNTRY_TH":          208,
		"TJ":                  209,
		"COUNTRY_TJ":          209,
		"TK":                  210,
		"COUNTRY_TK":          210,
		"TM":                  211,
		"COUNTRY_TM":          211,
		"TN":                  212,
		"COUNTRY_TN":          212,
		"TO":                  213,
		"COUNTRY_TO":          213,
		"TP":                  214,
		"COUNTRY_TP":          214,
		"TR":                  215,
		"COUNTRY_TR":          215,
		"TT":                  216,
		"COUNTRY_TT":          216,
		"TV":                  217,
		"COUNTRY_TV":          217,
		"TW":                  218,
		"COUNTRY_TW":          218,
		"TZ":                  219,
		"COUNTRY_TZ":          219,
		"UA":                  220,
		"COUNTRY_UA":          220,
		"UG":                  221,
		"COUNTRY_UG":          221,
		"UK":                  222,
		"COUNTRY_UK":          222,
		"UM":                  223,
		"COUNTRY_UM":          223,
		"US":                  224,
		"COUNTRY_US":          224,
		"UY":                  225,
		"COUNTRY_UY":          225,
		"UZ":                  226,
		"COUNTRY_UZ":          226,
		"VA":                  227,
		"COUNTRY_VA":          227,
		"VC":                  228,
		"COUNTRY_VC":          228,
		"VE":                  229,
		"COUNTRY_VE":          229,
		"VG":                  230,
		"COUNTRY_VG":          230,
		"VI":                  231,
		"COUNTRY_VI":          231,
		"VN":                  232,
		"COUNTRY_VN":          232,
		"VU":                  233,
		"COUNTRY_VU":          233,
		"WF":                  234,
		"COUNTRY_WF":          234,
		"WS":                  235,
		"COUNTRY_WS":          235,
		"YE":                  236,
		"COUNTRY_YE":          236,
		"YT":                  237,
		"COUNTRY_YT":          237,
		"YU":                  238,
		"COUNTRY_YU":          238,
		"ZA":                  239,
		"COUNTRY_ZA":          239,
		"ZM":                  240,
		"COUNTRY_ZM":          240,
		"ZR":                  241,
		"COUNTRY_ZR":          241,
		"ZW":                  242,
		"COUNTRY_ZW":          242,
	}
)

// ShortString returns the un-prefixed string representation of the enum value
func (x Country) ShortString() string {
	return Country_name_short[int32(x)]
}
func (x Country) Value() (driver.Value, error) {
	return []uint8(x.ShortString()), nil
}
func (x *Country) Scan(value interface{}) error {
	var strVal string
	switch vt := value.(type) {
	case []uint8:
		strVal = string(vt)
	case string:
		strVal = vt
	default:
		return fmt.Errorf("invalid type %T", value)
	}
	val := Country_value_either[strVal]
	*x = Country(val)
	return nil
}
