// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package iso_pb

import (
	driver "database/sql/driver"
	fmt "fmt"
)

// Country
const (
	Country_UNSPECIFIED Country = 0
	Country_AD          Country = 1
	Country_AF          Country = 2
	Country_AI          Country = 3
	Country_AM          Country = 4
	Country_AO          Country = 5
	Country_AR          Country = 6
	Country_AT          Country = 7
	Country_AW          Country = 8
	Country_BA          Country = 9
	Country_BD          Country = 10
	Country_BF          Country = 11
	Country_BH          Country = 12
	Country_BJ          Country = 13
	Country_BN          Country = 14
	Country_BR          Country = 15
	Country_BT          Country = 16
	Country_BW          Country = 17
	Country_BZ          Country = 18
	Country_CC          Country = 19
	Country_CG          Country = 20
	Country_CI          Country = 21
	Country_CL          Country = 22
	Country_CN          Country = 23
	Country_CR          Country = 24
	Country_CU          Country = 25
	Country_CX          Country = 26
	Country_CZ          Country = 27
	Country_DJ          Country = 28
	Country_DM          Country = 29
	Country_DZ          Country = 30
	Country_EE          Country = 31
	Country_EH          Country = 32
	Country_ES          Country = 33
	Country_FI          Country = 34
	Country_FK          Country = 35
	Country_FO          Country = 36
	Country_FX          Country = 37
	Country_GB          Country = 38
	Country_GE          Country = 39
	Country_GH          Country = 40
	Country_GL          Country = 41
	Country_GN          Country = 42
	Country_GQ          Country = 43
	Country_GS          Country = 44
	Country_GU          Country = 45
	Country_GY          Country = 46
	Country_HM          Country = 47
	Country_HR          Country = 48
	Country_HU          Country = 49
	Country_IE          Country = 50
	Country_IN          Country = 51
	Country_IQ          Country = 52
	Country_IS          Country = 53
	Country_JM          Country = 54
	Country_JP          Country = 55
	Country_KG          Country = 56
	Country_KI          Country = 57
	Country_KN          Country = 58
	Country_KR          Country = 59
	Country_KY          Country = 60
	Country_LA          Country = 61
	Country_LC          Country = 62
	Country_LK          Country = 63
	Country_LS          Country = 64
	Country_LU          Country = 65
	Country_LY          Country = 66
	Country_MC          Country = 67
	Country_MG          Country = 68
	Country_MK          Country = 69
	Country_MM          Country = 70
	Country_MO          Country = 71
	Country_MQ          Country = 72
	Country_MS          Country = 73
	Country_MU          Country = 74
	Country_MW          Country = 75
	Country_MY          Country = 76
	Country_NA          Country = 77
	Country_NE          Country = 78
	Country_NG          Country = 79
	Country_NL          Country = 80
	Country_NP          Country = 81
	Country_NU          Country = 82
	Country_OM          Country = 83
	Country_PE          Country = 84
	Country_PG          Country = 85
	Country_PK          Country = 86
	Country_PM          Country = 87
	Country_PR          Country = 88
	Country_PW          Country = 89
	Country_QA          Country = 90
	Country_RO          Country = 91
	Country_RW          Country = 92
	Country_SB          Country = 93
	Country_SD          Country = 94
	Country_SG          Country = 95
	Country_SI          Country = 96
	Country_SK          Country = 97
	Country_SM          Country = 98
	Country_SO          Country = 99
	Country_ST          Country = 100
	Country_SV          Country = 101
	Country_SZ          Country = 102
	Country_TD          Country = 103
	Country_TG          Country = 104
	Country_TJ          Country = 105
	Country_TM          Country = 106
	Country_TO          Country = 107
	Country_TR          Country = 108
	Country_TV          Country = 109
	Country_TZ          Country = 110
	Country_UG          Country = 111
	Country_UM          Country = 112
	Country_UY          Country = 113
	Country_VA          Country = 114
	Country_VE          Country = 115
	Country_VI          Country = 116
	Country_VU          Country = 117
	Country_WS          Country = 118
	Country_YT          Country = 119
	Country_ZA          Country = 120
	Country_ZR          Country = 121
	Country_AE          Country = 122
	Country_AG          Country = 123
	Country_AL          Country = 124
	Country_AN          Country = 125
	Country_AQ          Country = 126
	Country_AS          Country = 127
	Country_AU          Country = 128
	Country_AZ          Country = 129
	Country_BB          Country = 130
	Country_BE          Country = 131
	Country_BG          Country = 132
	Country_BI          Country = 133
	Country_BM          Country = 134
	Country_BO          Country = 135
	Country_BS          Country = 136
	Country_BV          Country = 137
	Country_BY          Country = 138
	Country_CA          Country = 139
	Country_CF          Country = 140
	Country_CH          Country = 141
	Country_CK          Country = 142
	Country_CM          Country = 143
	Country_CO          Country = 144
	Country_CS          Country = 145
	Country_CV          Country = 146
	Country_CY          Country = 147
	Country_DE          Country = 148
	Country_DK          Country = 149
	Country_DO          Country = 150
	Country_EC          Country = 151
	Country_EG          Country = 152
	Country_ER          Country = 153
	Country_ET          Country = 154
	Country_FJ          Country = 155
	Country_FM          Country = 156
	Country_FR          Country = 157
	Country_GA          Country = 158
	Country_GD          Country = 159
	Country_GF          Country = 160
	Country_GI          Country = 161
	Country_GM          Country = 162
	Country_GP          Country = 163
	Country_GR          Country = 164
	Country_GT          Country = 165
	Country_GW          Country = 166
	Country_HK          Country = 167
	Country_HN          Country = 168
	Country_HT          Country = 169
	Country_ID          Country = 170
	Country_IL          Country = 171
	Country_IO          Country = 172
	Country_IR          Country = 173
	Country_IT          Country = 174
	Country_JO          Country = 175
	Country_KE          Country = 176
	Country_KH          Country = 177
	Country_KM          Country = 178
	Country_KP          Country = 179
	Country_KW          Country = 180
	Country_KZ          Country = 181
	Country_LB          Country = 182
	Country_LI          Country = 183
	Country_LR          Country = 184
	Country_LT          Country = 185
	Country_LV          Country = 186
	Country_MA          Country = 187
	Country_MD          Country = 188
	Country_MH          Country = 189
	Country_ML          Country = 190
	Country_MN          Country = 191
	Country_MP          Country = 192
	Country_MR          Country = 193
	Country_MT          Country = 194
	Country_MV          Country = 195
	Country_MX          Country = 196
	Country_MZ          Country = 197
	Country_NC          Country = 198
	Country_NF          Country = 199
	Country_NI          Country = 200
	Country_NO          Country = 201
	Country_NR          Country = 202
	Country_NZ          Country = 203
	Country_PA          Country = 204
	Country_PF          Country = 205
	Country_PH          Country = 206
	Country_PL          Country = 207
	Country_PN          Country = 208
	Country_PT          Country = 209
	Country_PY          Country = 210
	Country_RE          Country = 211
	Country_RU          Country = 212
	Country_SA          Country = 213
	Country_SC          Country = 214
	Country_SE          Country = 215
	Country_SH          Country = 216
	Country_SJ          Country = 217
	Country_SL          Country = 218
	Country_SN          Country = 219
	Country_SR          Country = 220
	Country_SU          Country = 221
	Country_SY          Country = 222
	Country_TC          Country = 223
	Country_TF          Country = 224
	Country_TH          Country = 225
	Country_TK          Country = 226
	Country_TN          Country = 227
	Country_TP          Country = 228
	Country_TT          Country = 229
	Country_TW          Country = 230
	Country_UA          Country = 231
	Country_UK          Country = 232
	Country_US          Country = 233
	Country_UZ          Country = 234
	Country_VC          Country = 235
	Country_VG          Country = 236
	Country_VN          Country = 237
	Country_WF          Country = 238
	Country_YE          Country = 239
	Country_YU          Country = 240
	Country_ZM          Country = 241
	Country_ZW          Country = 242
)

var (
	Country_name_short = map[int32]string{
		0:   "UNSPECIFIED",
		1:   "AD",
		2:   "AF",
		3:   "AI",
		4:   "AM",
		5:   "AO",
		6:   "AR",
		7:   "AT",
		8:   "AW",
		9:   "BA",
		10:  "BD",
		11:  "BF",
		12:  "BH",
		13:  "BJ",
		14:  "BN",
		15:  "BR",
		16:  "BT",
		17:  "BW",
		18:  "BZ",
		19:  "CC",
		20:  "CG",
		21:  "CI",
		22:  "CL",
		23:  "CN",
		24:  "CR",
		25:  "CU",
		26:  "CX",
		27:  "CZ",
		28:  "DJ",
		29:  "DM",
		30:  "DZ",
		31:  "EE",
		32:  "EH",
		33:  "ES",
		34:  "FI",
		35:  "FK",
		36:  "FO",
		37:  "FX",
		38:  "GB",
		39:  "GE",
		40:  "GH",
		41:  "GL",
		42:  "GN",
		43:  "GQ",
		44:  "GS",
		45:  "GU",
		46:  "GY",
		47:  "HM",
		48:  "HR",
		49:  "HU",
		50:  "IE",
		51:  "IN",
		52:  "IQ",
		53:  "IS",
		54:  "JM",
		55:  "JP",
		56:  "KG",
		57:  "KI",
		58:  "KN",
		59:  "KR",
		60:  "KY",
		61:  "LA",
		62:  "LC",
		63:  "LK",
		64:  "LS",
		65:  "LU",
		66:  "LY",
		67:  "MC",
		68:  "MG",
		69:  "MK",
		70:  "MM",
		71:  "MO",
		72:  "MQ",
		73:  "MS",
		74:  "MU",
		75:  "MW",
		76:  "MY",
		77:  "NA",
		78:  "NE",
		79:  "NG",
		80:  "NL",
		81:  "NP",
		82:  "NU",
		83:  "OM",
		84:  "PE",
		85:  "PG",
		86:  "PK",
		87:  "PM",
		88:  "PR",
		89:  "PW",
		90:  "QA",
		91:  "RO",
		92:  "RW",
		93:  "SB",
		94:  "SD",
		95:  "SG",
		96:  "SI",
		97:  "SK",
		98:  "SM",
		99:  "SO",
		100: "ST",
		101: "SV",
		102: "SZ",
		103: "TD",
		104: "TG",
		105: "TJ",
		106: "TM",
		107: "TO",
		108: "TR",
		109: "TV",
		110: "TZ",
		111: "UG",
		112: "UM",
		113: "UY",
		114: "VA",
		115: "VE",
		116: "VI",
		117: "VU",
		118: "WS",
		119: "YT",
		120: "ZA",
		121: "ZR",
		122: "AE",
		123: "AG",
		124: "AL",
		125: "AN",
		126: "AQ",
		127: "AS",
		128: "AU",
		129: "AZ",
		130: "BB",
		131: "BE",
		132: "BG",
		133: "BI",
		134: "BM",
		135: "BO",
		136: "BS",
		137: "BV",
		138: "BY",
		139: "CA",
		140: "CF",
		141: "CH",
		142: "CK",
		143: "CM",
		144: "CO",
		145: "CS",
		146: "CV",
		147: "CY",
		148: "DE",
		149: "DK",
		150: "DO",
		151: "EC",
		152: "EG",
		153: "ER",
		154: "ET",
		155: "FJ",
		156: "FM",
		157: "FR",
		158: "GA",
		159: "GD",
		160: "GF",
		161: "GI",
		162: "GM",
		163: "GP",
		164: "GR",
		165: "GT",
		166: "GW",
		167: "HK",
		168: "HN",
		169: "HT",
		170: "ID",
		171: "IL",
		172: "IO",
		173: "IR",
		174: "IT",
		175: "JO",
		176: "KE",
		177: "KH",
		178: "KM",
		179: "KP",
		180: "KW",
		181: "KZ",
		182: "LB",
		183: "LI",
		184: "LR",
		185: "LT",
		186: "LV",
		187: "MA",
		188: "MD",
		189: "MH",
		190: "ML",
		191: "MN",
		192: "MP",
		193: "MR",
		194: "MT",
		195: "MV",
		196: "MX",
		197: "MZ",
		198: "NC",
		199: "NF",
		200: "NI",
		201: "NO",
		202: "NR",
		203: "NZ",
		204: "PA",
		205: "PF",
		206: "PH",
		207: "PL",
		208: "PN",
		209: "PT",
		210: "PY",
		211: "RE",
		212: "RU",
		213: "SA",
		214: "SC",
		215: "SE",
		216: "SH",
		217: "SJ",
		218: "SL",
		219: "SN",
		220: "SR",
		221: "SU",
		222: "SY",
		223: "TC",
		224: "TF",
		225: "TH",
		226: "TK",
		227: "TN",
		228: "TP",
		229: "TT",
		230: "TW",
		231: "UA",
		232: "UK",
		233: "US",
		234: "UZ",
		235: "VC",
		236: "VG",
		237: "VN",
		238: "WF",
		239: "YE",
		240: "YU",
		241: "ZM",
		242: "ZW",
	}
	Country_value_short = map[string]int32{
		"UNSPECIFIED": 0,
		"AD":          1,
		"AF":          2,
		"AI":          3,
		"AM":          4,
		"AO":          5,
		"AR":          6,
		"AT":          7,
		"AW":          8,
		"BA":          9,
		"BD":          10,
		"BF":          11,
		"BH":          12,
		"BJ":          13,
		"BN":          14,
		"BR":          15,
		"BT":          16,
		"BW":          17,
		"BZ":          18,
		"CC":          19,
		"CG":          20,
		"CI":          21,
		"CL":          22,
		"CN":          23,
		"CR":          24,
		"CU":          25,
		"CX":          26,
		"CZ":          27,
		"DJ":          28,
		"DM":          29,
		"DZ":          30,
		"EE":          31,
		"EH":          32,
		"ES":          33,
		"FI":          34,
		"FK":          35,
		"FO":          36,
		"FX":          37,
		"GB":          38,
		"GE":          39,
		"GH":          40,
		"GL":          41,
		"GN":          42,
		"GQ":          43,
		"GS":          44,
		"GU":          45,
		"GY":          46,
		"HM":          47,
		"HR":          48,
		"HU":          49,
		"IE":          50,
		"IN":          51,
		"IQ":          52,
		"IS":          53,
		"JM":          54,
		"JP":          55,
		"KG":          56,
		"KI":          57,
		"KN":          58,
		"KR":          59,
		"KY":          60,
		"LA":          61,
		"LC":          62,
		"LK":          63,
		"LS":          64,
		"LU":          65,
		"LY":          66,
		"MC":          67,
		"MG":          68,
		"MK":          69,
		"MM":          70,
		"MO":          71,
		"MQ":          72,
		"MS":          73,
		"MU":          74,
		"MW":          75,
		"MY":          76,
		"NA":          77,
		"NE":          78,
		"NG":          79,
		"NL":          80,
		"NP":          81,
		"NU":          82,
		"OM":          83,
		"PE":          84,
		"PG":          85,
		"PK":          86,
		"PM":          87,
		"PR":          88,
		"PW":          89,
		"QA":          90,
		"RO":          91,
		"RW":          92,
		"SB":          93,
		"SD":          94,
		"SG":          95,
		"SI":          96,
		"SK":          97,
		"SM":          98,
		"SO":          99,
		"ST":          100,
		"SV":          101,
		"SZ":          102,
		"TD":          103,
		"TG":          104,
		"TJ":          105,
		"TM":          106,
		"TO":          107,
		"TR":          108,
		"TV":          109,
		"TZ":          110,
		"UG":          111,
		"UM":          112,
		"UY":          113,
		"VA":          114,
		"VE":          115,
		"VI":          116,
		"VU":          117,
		"WS":          118,
		"YT":          119,
		"ZA":          120,
		"ZR":          121,
		"AE":          122,
		"AG":          123,
		"AL":          124,
		"AN":          125,
		"AQ":          126,
		"AS":          127,
		"AU":          128,
		"AZ":          129,
		"BB":          130,
		"BE":          131,
		"BG":          132,
		"BI":          133,
		"BM":          134,
		"BO":          135,
		"BS":          136,
		"BV":          137,
		"BY":          138,
		"CA":          139,
		"CF":          140,
		"CH":          141,
		"CK":          142,
		"CM":          143,
		"CO":          144,
		"CS":          145,
		"CV":          146,
		"CY":          147,
		"DE":          148,
		"DK":          149,
		"DO":          150,
		"EC":          151,
		"EG":          152,
		"ER":          153,
		"ET":          154,
		"FJ":          155,
		"FM":          156,
		"FR":          157,
		"GA":          158,
		"GD":          159,
		"GF":          160,
		"GI":          161,
		"GM":          162,
		"GP":          163,
		"GR":          164,
		"GT":          165,
		"GW":          166,
		"HK":          167,
		"HN":          168,
		"HT":          169,
		"ID":          170,
		"IL":          171,
		"IO":          172,
		"IR":          173,
		"IT":          174,
		"JO":          175,
		"KE":          176,
		"KH":          177,
		"KM":          178,
		"KP":          179,
		"KW":          180,
		"KZ":          181,
		"LB":          182,
		"LI":          183,
		"LR":          184,
		"LT":          185,
		"LV":          186,
		"MA":          187,
		"MD":          188,
		"MH":          189,
		"ML":          190,
		"MN":          191,
		"MP":          192,
		"MR":          193,
		"MT":          194,
		"MV":          195,
		"MX":          196,
		"MZ":          197,
		"NC":          198,
		"NF":          199,
		"NI":          200,
		"NO":          201,
		"NR":          202,
		"NZ":          203,
		"PA":          204,
		"PF":          205,
		"PH":          206,
		"PL":          207,
		"PN":          208,
		"PT":          209,
		"PY":          210,
		"RE":          211,
		"RU":          212,
		"SA":          213,
		"SC":          214,
		"SE":          215,
		"SH":          216,
		"SJ":          217,
		"SL":          218,
		"SN":          219,
		"SR":          220,
		"SU":          221,
		"SY":          222,
		"TC":          223,
		"TF":          224,
		"TH":          225,
		"TK":          226,
		"TN":          227,
		"TP":          228,
		"TT":          229,
		"TW":          230,
		"UA":          231,
		"UK":          232,
		"US":          233,
		"UZ":          234,
		"VC":          235,
		"VG":          236,
		"VN":          237,
		"WF":          238,
		"YE":          239,
		"YU":          240,
		"ZM":          241,
		"ZW":          242,
	}
	Country_value_either = map[string]int32{
		"UNSPECIFIED":         0,
		"COUNTRY_UNSPECIFIED": 0,
		"AD":                  1,
		"COUNTRY_AD":          1,
		"AF":                  2,
		"COUNTRY_AF":          2,
		"AI":                  3,
		"COUNTRY_AI":          3,
		"AM":                  4,
		"COUNTRY_AM":          4,
		"AO":                  5,
		"COUNTRY_AO":          5,
		"AR":                  6,
		"COUNTRY_AR":          6,
		"AT":                  7,
		"COUNTRY_AT":          7,
		"AW":                  8,
		"COUNTRY_AW":          8,
		"BA":                  9,
		"COUNTRY_BA":          9,
		"BD":                  10,
		"COUNTRY_BD":          10,
		"BF":                  11,
		"COUNTRY_BF":          11,
		"BH":                  12,
		"COUNTRY_BH":          12,
		"BJ":                  13,
		"COUNTRY_BJ":          13,
		"BN":                  14,
		"COUNTRY_BN":          14,
		"BR":                  15,
		"COUNTRY_BR":          15,
		"BT":                  16,
		"COUNTRY_BT":          16,
		"BW":                  17,
		"COUNTRY_BW":          17,
		"BZ":                  18,
		"COUNTRY_BZ":          18,
		"CC":                  19,
		"COUNTRY_CC":          19,
		"CG":                  20,
		"COUNTRY_CG":          20,
		"CI":                  21,
		"COUNTRY_CI":          21,
		"CL":                  22,
		"COUNTRY_CL":          22,
		"CN":                  23,
		"COUNTRY_CN":          23,
		"CR":                  24,
		"COUNTRY_CR":          24,
		"CU":                  25,
		"COUNTRY_CU":          25,
		"CX":                  26,
		"COUNTRY_CX":          26,
		"CZ":                  27,
		"COUNTRY_CZ":          27,
		"DJ":                  28,
		"COUNTRY_DJ":          28,
		"DM":                  29,
		"COUNTRY_DM":          29,
		"DZ":                  30,
		"COUNTRY_DZ":          30,
		"EE":                  31,
		"COUNTRY_EE":          31,
		"EH":                  32,
		"COUNTRY_EH":          32,
		"ES":                  33,
		"COUNTRY_ES":          33,
		"FI":                  34,
		"COUNTRY_FI":          34,
		"FK":                  35,
		"COUNTRY_FK":          35,
		"FO":                  36,
		"COUNTRY_FO":          36,
		"FX":                  37,
		"COUNTRY_FX":          37,
		"GB":                  38,
		"COUNTRY_GB":          38,
		"GE":                  39,
		"COUNTRY_GE":          39,
		"GH":                  40,
		"COUNTRY_GH":          40,
		"GL":                  41,
		"COUNTRY_GL":          41,
		"GN":                  42,
		"COUNTRY_GN":          42,
		"GQ":                  43,
		"COUNTRY_GQ":          43,
		"GS":                  44,
		"COUNTRY_GS":          44,
		"GU":                  45,
		"COUNTRY_GU":          45,
		"GY":                  46,
		"COUNTRY_GY":          46,
		"HM":                  47,
		"COUNTRY_HM":          47,
		"HR":                  48,
		"COUNTRY_HR":          48,
		"HU":                  49,
		"COUNTRY_HU":          49,
		"IE":                  50,
		"COUNTRY_IE":          50,
		"IN":                  51,
		"COUNTRY_IN":          51,
		"IQ":                  52,
		"COUNTRY_IQ":          52,
		"IS":                  53,
		"COUNTRY_IS":          53,
		"JM":                  54,
		"COUNTRY_JM":          54,
		"JP":                  55,
		"COUNTRY_JP":          55,
		"KG":                  56,
		"COUNTRY_KG":          56,
		"KI":                  57,
		"COUNTRY_KI":          57,
		"KN":                  58,
		"COUNTRY_KN":          58,
		"KR":                  59,
		"COUNTRY_KR":          59,
		"KY":                  60,
		"COUNTRY_KY":          60,
		"LA":                  61,
		"COUNTRY_LA":          61,
		"LC":                  62,
		"COUNTRY_LC":          62,
		"LK":                  63,
		"COUNTRY_LK":          63,
		"LS":                  64,
		"COUNTRY_LS":          64,
		"LU":                  65,
		"COUNTRY_LU":          65,
		"LY":                  66,
		"COUNTRY_LY":          66,
		"MC":                  67,
		"COUNTRY_MC":          67,
		"MG":                  68,
		"COUNTRY_MG":          68,
		"MK":                  69,
		"COUNTRY_MK":          69,
		"MM":                  70,
		"COUNTRY_MM":          70,
		"MO":                  71,
		"COUNTRY_MO":          71,
		"MQ":                  72,
		"COUNTRY_MQ":          72,
		"MS":                  73,
		"COUNTRY_MS":          73,
		"MU":                  74,
		"COUNTRY_MU":          74,
		"MW":                  75,
		"COUNTRY_MW":          75,
		"MY":                  76,
		"COUNTRY_MY":          76,
		"NA":                  77,
		"COUNTRY_NA":          77,
		"NE":                  78,
		"COUNTRY_NE":          78,
		"NG":                  79,
		"COUNTRY_NG":          79,
		"NL":                  80,
		"COUNTRY_NL":          80,
		"NP":                  81,
		"COUNTRY_NP":          81,
		"NU":                  82,
		"COUNTRY_NU":          82,
		"OM":                  83,
		"COUNTRY_OM":          83,
		"PE":                  84,
		"COUNTRY_PE":          84,
		"PG":                  85,
		"COUNTRY_PG":          85,
		"PK":                  86,
		"COUNTRY_PK":          86,
		"PM":                  87,
		"COUNTRY_PM":          87,
		"PR":                  88,
		"COUNTRY_PR":          88,
		"PW":                  89,
		"COUNTRY_PW":          89,
		"QA":                  90,
		"COUNTRY_QA":          90,
		"RO":                  91,
		"COUNTRY_RO":          91,
		"RW":                  92,
		"COUNTRY_RW":          92,
		"SB":                  93,
		"COUNTRY_SB":          93,
		"SD":                  94,
		"COUNTRY_SD":          94,
		"SG":                  95,
		"COUNTRY_SG":          95,
		"SI":                  96,
		"COUNTRY_SI":          96,
		"SK":                  97,
		"COUNTRY_SK":          97,
		"SM":                  98,
		"COUNTRY_SM":          98,
		"SO":                  99,
		"COUNTRY_SO":          99,
		"ST":                  100,
		"COUNTRY_ST":          100,
		"SV":                  101,
		"COUNTRY_SV":          101,
		"SZ":                  102,
		"COUNTRY_SZ":          102,
		"TD":                  103,
		"COUNTRY_TD":          103,
		"TG":                  104,
		"COUNTRY_TG":          104,
		"TJ":                  105,
		"COUNTRY_TJ":          105,
		"TM":                  106,
		"COUNTRY_TM":          106,
		"TO":                  107,
		"COUNTRY_TO":          107,
		"TR":                  108,
		"COUNTRY_TR":          108,
		"TV":                  109,
		"COUNTRY_TV":          109,
		"TZ":                  110,
		"COUNTRY_TZ":          110,
		"UG":                  111,
		"COUNTRY_UG":          111,
		"UM":                  112,
		"COUNTRY_UM":          112,
		"UY":                  113,
		"COUNTRY_UY":          113,
		"VA":                  114,
		"COUNTRY_VA":          114,
		"VE":                  115,
		"COUNTRY_VE":          115,
		"VI":                  116,
		"COUNTRY_VI":          116,
		"VU":                  117,
		"COUNTRY_VU":          117,
		"WS":                  118,
		"COUNTRY_WS":          118,
		"YT":                  119,
		"COUNTRY_YT":          119,
		"ZA":                  120,
		"COUNTRY_ZA":          120,
		"ZR":                  121,
		"COUNTRY_ZR":          121,
		"AE":                  122,
		"COUNTRY_AE":          122,
		"AG":                  123,
		"COUNTRY_AG":          123,
		"AL":                  124,
		"COUNTRY_AL":          124,
		"AN":                  125,
		"COUNTRY_AN":          125,
		"AQ":                  126,
		"COUNTRY_AQ":          126,
		"AS":                  127,
		"COUNTRY_AS":          127,
		"AU":                  128,
		"COUNTRY_AU":          128,
		"AZ":                  129,
		"COUNTRY_AZ":          129,
		"BB":                  130,
		"COUNTRY_BB":          130,
		"BE":                  131,
		"COUNTRY_BE":          131,
		"BG":                  132,
		"COUNTRY_BG":          132,
		"BI":                  133,
		"COUNTRY_BI":          133,
		"BM":                  134,
		"COUNTRY_BM":          134,
		"BO":                  135,
		"COUNTRY_BO":          135,
		"BS":                  136,
		"COUNTRY_BS":          136,
		"BV":                  137,
		"COUNTRY_BV":          137,
		"BY":                  138,
		"COUNTRY_BY":          138,
		"CA":                  139,
		"COUNTRY_CA":          139,
		"CF":                  140,
		"COUNTRY_CF":          140,
		"CH":                  141,
		"COUNTRY_CH":          141,
		"CK":                  142,
		"COUNTRY_CK":          142,
		"CM":                  143,
		"COUNTRY_CM":          143,
		"CO":                  144,
		"COUNTRY_CO":          144,
		"CS":                  145,
		"COUNTRY_CS":          145,
		"CV":                  146,
		"COUNTRY_CV":          146,
		"CY":                  147,
		"COUNTRY_CY":          147,
		"DE":                  148,
		"COUNTRY_DE":          148,
		"DK":                  149,
		"COUNTRY_DK":          149,
		"DO":                  150,
		"COUNTRY_DO":          150,
		"EC":                  151,
		"COUNTRY_EC":          151,
		"EG":                  152,
		"COUNTRY_EG":          152,
		"ER":                  153,
		"COUNTRY_ER":          153,
		"ET":                  154,
		"COUNTRY_ET":          154,
		"FJ":                  155,
		"COUNTRY_FJ":          155,
		"FM":                  156,
		"COUNTRY_FM":          156,
		"FR":                  157,
		"COUNTRY_FR":          157,
		"GA":                  158,
		"COUNTRY_GA":          158,
		"GD":                  159,
		"COUNTRY_GD":          159,
		"GF":                  160,
		"COUNTRY_GF":          160,
		"GI":                  161,
		"COUNTRY_GI":          161,
		"GM":                  162,
		"COUNTRY_GM":          162,
		"GP":                  163,
		"COUNTRY_GP":          163,
		"GR":                  164,
		"COUNTRY_GR":          164,
		"GT":                  165,
		"COUNTRY_GT":          165,
		"GW":                  166,
		"COUNTRY_GW":          166,
		"HK":                  167,
		"COUNTRY_HK":          167,
		"HN":                  168,
		"COUNTRY_HN":          168,
		"HT":                  169,
		"COUNTRY_HT":          169,
		"ID":                  170,
		"COUNTRY_ID":          170,
		"IL":                  171,
		"COUNTRY_IL":          171,
		"IO":                  172,
		"COUNTRY_IO":          172,
		"IR":                  173,
		"COUNTRY_IR":          173,
		"IT":                  174,
		"COUNTRY_IT":          174,
		"JO":                  175,
		"COUNTRY_JO":          175,
		"KE":                  176,
		"COUNTRY_KE":          176,
		"KH":                  177,
		"COUNTRY_KH":          177,
		"KM":                  178,
		"COUNTRY_KM":          178,
		"KP":                  179,
		"COUNTRY_KP":          179,
		"KW":                  180,
		"COUNTRY_KW":          180,
		"KZ":                  181,
		"COUNTRY_KZ":          181,
		"LB":                  182,
		"COUNTRY_LB":          182,
		"LI":                  183,
		"COUNTRY_LI":          183,
		"LR":                  184,
		"COUNTRY_LR":          184,
		"LT":                  185,
		"COUNTRY_LT":          185,
		"LV":                  186,
		"COUNTRY_LV":          186,
		"MA":                  187,
		"COUNTRY_MA":          187,
		"MD":                  188,
		"COUNTRY_MD":          188,
		"MH":                  189,
		"COUNTRY_MH":          189,
		"ML":                  190,
		"COUNTRY_ML":          190,
		"MN":                  191,
		"COUNTRY_MN":          191,
		"MP":                  192,
		"COUNTRY_MP":          192,
		"MR":                  193,
		"COUNTRY_MR":          193,
		"MT":                  194,
		"COUNTRY_MT":          194,
		"MV":                  195,
		"COUNTRY_MV":          195,
		"MX":                  196,
		"COUNTRY_MX":          196,
		"MZ":                  197,
		"COUNTRY_MZ":          197,
		"NC":                  198,
		"COUNTRY_NC":          198,
		"NF":                  199,
		"COUNTRY_NF":          199,
		"NI":                  200,
		"COUNTRY_NI":          200,
		"NO":                  201,
		"COUNTRY_NO":          201,
		"NR":                  202,
		"COUNTRY_NR":          202,
		"NZ":                  203,
		"COUNTRY_NZ":          203,
		"PA":                  204,
		"COUNTRY_PA":          204,
		"PF":                  205,
		"COUNTRY_PF":          205,
		"PH":                  206,
		"COUNTRY_PH":          206,
		"PL":                  207,
		"COUNTRY_PL":          207,
		"PN":                  208,
		"COUNTRY_PN":          208,
		"PT":                  209,
		"COUNTRY_PT":          209,
		"PY":                  210,
		"COUNTRY_PY":          210,
		"RE":                  211,
		"COUNTRY_RE":          211,
		"RU":                  212,
		"COUNTRY_RU":          212,
		"SA":                  213,
		"COUNTRY_SA":          213,
		"SC":                  214,
		"COUNTRY_SC":          214,
		"SE":                  215,
		"COUNTRY_SE":          215,
		"SH":                  216,
		"COUNTRY_SH":          216,
		"SJ":                  217,
		"COUNTRY_SJ":          217,
		"SL":                  218,
		"COUNTRY_SL":          218,
		"SN":                  219,
		"COUNTRY_SN":          219,
		"SR":                  220,
		"COUNTRY_SR":          220,
		"SU":                  221,
		"COUNTRY_SU":          221,
		"SY":                  222,
		"COUNTRY_SY":          222,
		"TC":                  223,
		"COUNTRY_TC":          223,
		"TF":                  224,
		"COUNTRY_TF":          224,
		"TH":                  225,
		"COUNTRY_TH":          225,
		"TK":                  226,
		"COUNTRY_TK":          226,
		"TN":                  227,
		"COUNTRY_TN":          227,
		"TP":                  228,
		"COUNTRY_TP":          228,
		"TT":                  229,
		"COUNTRY_TT":          229,
		"TW":                  230,
		"COUNTRY_TW":          230,
		"UA":                  231,
		"COUNTRY_UA":          231,
		"UK":                  232,
		"COUNTRY_UK":          232,
		"US":                  233,
		"COUNTRY_US":          233,
		"UZ":                  234,
		"COUNTRY_UZ":          234,
		"VC":                  235,
		"COUNTRY_VC":          235,
		"VG":                  236,
		"COUNTRY_VG":          236,
		"VN":                  237,
		"COUNTRY_VN":          237,
		"WF":                  238,
		"COUNTRY_WF":          238,
		"YE":                  239,
		"COUNTRY_YE":          239,
		"YU":                  240,
		"COUNTRY_YU":          240,
		"ZM":                  241,
		"COUNTRY_ZM":          241,
		"ZW":                  242,
		"COUNTRY_ZW":          242,
	}
)

// ShortString returns the un-prefixed string representation of the enum value
func (x Country) ShortString() string {
	return Country_name_short[int32(x)]
}
func (x Country) Value() (driver.Value, error) {
	return []uint8(x.ShortString()), nil
}
func (x *Country) Scan(value interface{}) error {
	var strVal string
	switch vt := value.(type) {
	case []uint8:
		strVal = string(vt)
	case string:
		strVal = vt
	default:
		return fmt.Errorf("invalid type %T", value)
	}
	val := Country_value_either[strVal]
	*x = Country(val)
	return nil
}
