// Code generated by protoc-gen-go-sugar. DO NOT EDIT.

package iso_pb

import (
	driver "database/sql/driver"
	fmt "fmt"
)

// Currency
const (
	Currency_UNSPECIFIED Currency = 0
	Currency_AED         Currency = 1
	Currency_AFN         Currency = 2
	Currency_ALL         Currency = 3
	Currency_AMD         Currency = 4
	Currency_ANG         Currency = 5
	Currency_AOA         Currency = 6
	Currency_ARS         Currency = 7
	Currency_AUD         Currency = 8
	Currency_AWG         Currency = 9
	Currency_AZN         Currency = 10
	Currency_BAM         Currency = 11
	Currency_BBD         Currency = 12
	Currency_BDT         Currency = 13
	Currency_BGN         Currency = 14
	Currency_BHD         Currency = 15
	Currency_BIF         Currency = 16
	Currency_BMD         Currency = 17
	Currency_BND         Currency = 18
	Currency_BOB         Currency = 19
	Currency_BOV         Currency = 20
	Currency_BRL         Currency = 21
	Currency_BSD         Currency = 22
	Currency_BTN         Currency = 23
	Currency_BWP         Currency = 24
	Currency_BYN         Currency = 25
	Currency_BZD         Currency = 26
	Currency_CAD         Currency = 27
	Currency_CDF         Currency = 28
	Currency_CHE         Currency = 29
	Currency_CHF         Currency = 30
	Currency_CHW         Currency = 31
	Currency_CLF         Currency = 32
	Currency_CLP         Currency = 33
	Currency_CNY         Currency = 34
	Currency_COP         Currency = 35
	Currency_COU         Currency = 36
	Currency_CRC         Currency = 37
	Currency_CUC         Currency = 38
	Currency_CUP         Currency = 39
	Currency_CVE         Currency = 40
	Currency_CZK         Currency = 41
	Currency_DJF         Currency = 42
	Currency_DKK         Currency = 43
	Currency_DOP         Currency = 44
	Currency_DZD         Currency = 45
	Currency_EGP         Currency = 46
	Currency_ERN         Currency = 47
	Currency_ETB         Currency = 48
	Currency_EUR         Currency = 49
	Currency_FJD         Currency = 50
	Currency_FKP         Currency = 51
	Currency_GBP         Currency = 52
	Currency_GEL         Currency = 53
	Currency_GHS         Currency = 54
	Currency_GIP         Currency = 55
	Currency_GMD         Currency = 56
	Currency_GNF         Currency = 57
	Currency_GTQ         Currency = 58
	Currency_GYD         Currency = 59
	Currency_HKD         Currency = 60
	Currency_HNL         Currency = 61
	Currency_HRK         Currency = 62
	Currency_HTG         Currency = 63
	Currency_HUF         Currency = 64
	Currency_IDR         Currency = 65
	Currency_ILS         Currency = 66
	Currency_INR         Currency = 67
	Currency_IQD         Currency = 68
	Currency_IRR         Currency = 69
	Currency_ISK         Currency = 70
	Currency_JMD         Currency = 71
	Currency_JOD         Currency = 72
	Currency_JPY         Currency = 73
	Currency_KES         Currency = 74
	Currency_KGS         Currency = 75
	Currency_KHR         Currency = 76
	Currency_KMF         Currency = 77
	Currency_KPW         Currency = 78
	Currency_KRW         Currency = 79
	Currency_KWD         Currency = 80
	Currency_KYD         Currency = 81
	Currency_KZT         Currency = 82
	Currency_LAK         Currency = 83
	Currency_LBP         Currency = 84
	Currency_LKR         Currency = 85
	Currency_LRD         Currency = 86
	Currency_LSL         Currency = 87
	Currency_LYD         Currency = 88
	Currency_MAD         Currency = 89
	Currency_MDL         Currency = 90
	Currency_MGA         Currency = 91
	Currency_MKD         Currency = 92
	Currency_MMK         Currency = 93
	Currency_MNT         Currency = 94
	Currency_MOP         Currency = 95
	Currency_MRU         Currency = 96
	Currency_MUR         Currency = 97
	Currency_MVR         Currency = 98
	Currency_MWK         Currency = 99
	Currency_MXN         Currency = 100
	Currency_MXV         Currency = 101
	Currency_MYR         Currency = 102
	Currency_MZN         Currency = 103
	Currency_NAD         Currency = 104
	Currency_NGN         Currency = 105
	Currency_NIO         Currency = 106
	Currency_NOK         Currency = 107
	Currency_NPR         Currency = 108
	Currency_NZD         Currency = 109
	Currency_OMR         Currency = 110
	Currency_PAB         Currency = 111
	Currency_PEN         Currency = 112
	Currency_PGK         Currency = 113
	Currency_PHP         Currency = 114
	Currency_PKR         Currency = 115
	Currency_PLN         Currency = 116
	Currency_PYG         Currency = 117
	Currency_QAR         Currency = 118
	Currency_RON         Currency = 119
	Currency_RSD         Currency = 120
	Currency_RUB         Currency = 121
	Currency_RWF         Currency = 122
	Currency_SAR         Currency = 123
	Currency_SBD         Currency = 124
	Currency_SCR         Currency = 125
	Currency_SDG         Currency = 126
	Currency_SEK         Currency = 127
	Currency_SGD         Currency = 128
	Currency_SHP         Currency = 129
	Currency_SLL         Currency = 130
	Currency_SOS         Currency = 131
	Currency_SRD         Currency = 132
	Currency_SSP         Currency = 133
	Currency_STN         Currency = 134
	Currency_SVC         Currency = 135
	Currency_SYP         Currency = 136
	Currency_SZL         Currency = 137
	Currency_THB         Currency = 138
	Currency_TJS         Currency = 139
	Currency_TMT         Currency = 140
	Currency_TND         Currency = 141
	Currency_TOP         Currency = 142
	Currency_TRY         Currency = 143
	Currency_TTD         Currency = 144
	Currency_TWD         Currency = 145
	Currency_TZS         Currency = 146
	Currency_UAH         Currency = 147
	Currency_UGX         Currency = 148
	Currency_USD         Currency = 149
	Currency_USN         Currency = 150
	Currency_UYI         Currency = 151
	Currency_UYU         Currency = 152
	Currency_UYW         Currency = 153
	Currency_UZS         Currency = 154
	Currency_VED         Currency = 155
	Currency_VES         Currency = 156
	Currency_VND         Currency = 157
	Currency_VUV         Currency = 158
	Currency_WST         Currency = 159
	Currency_XAF         Currency = 160
	Currency_XAG         Currency = 161
	Currency_XAU         Currency = 162
	Currency_XBA         Currency = 163
	Currency_XBB         Currency = 164
	Currency_XBC         Currency = 165
	Currency_XBD         Currency = 166
	Currency_XCD         Currency = 167
	Currency_XDR         Currency = 168
	Currency_XOF         Currency = 169
	Currency_XPD         Currency = 170
	Currency_XPF         Currency = 171
	Currency_XPT         Currency = 172
	Currency_XSU         Currency = 173
	Currency_XTS         Currency = 174
	Currency_XUA         Currency = 175
	Currency_XXX         Currency = 176
	Currency_YER         Currency = 177
	Currency_ZAR         Currency = 178
	Currency_ZMW         Currency = 179
	Currency_ZWL         Currency = 180
)

var (
	Currency_name_short = map[int32]string{
		0:   "UNSPECIFIED",
		1:   "AED",
		2:   "AFN",
		3:   "ALL",
		4:   "AMD",
		5:   "ANG",
		6:   "AOA",
		7:   "ARS",
		8:   "AUD",
		9:   "AWG",
		10:  "AZN",
		11:  "BAM",
		12:  "BBD",
		13:  "BDT",
		14:  "BGN",
		15:  "BHD",
		16:  "BIF",
		17:  "BMD",
		18:  "BND",
		19:  "BOB",
		20:  "BOV",
		21:  "BRL",
		22:  "BSD",
		23:  "BTN",
		24:  "BWP",
		25:  "BYN",
		26:  "BZD",
		27:  "CAD",
		28:  "CDF",
		29:  "CHE",
		30:  "CHF",
		31:  "CHW",
		32:  "CLF",
		33:  "CLP",
		34:  "CNY",
		35:  "COP",
		36:  "COU",
		37:  "CRC",
		38:  "CUC",
		39:  "CUP",
		40:  "CVE",
		41:  "CZK",
		42:  "DJF",
		43:  "DKK",
		44:  "DOP",
		45:  "DZD",
		46:  "EGP",
		47:  "ERN",
		48:  "ETB",
		49:  "EUR",
		50:  "FJD",
		51:  "FKP",
		52:  "GBP",
		53:  "GEL",
		54:  "GHS",
		55:  "GIP",
		56:  "GMD",
		57:  "GNF",
		58:  "GTQ",
		59:  "GYD",
		60:  "HKD",
		61:  "HNL",
		62:  "HRK",
		63:  "HTG",
		64:  "HUF",
		65:  "IDR",
		66:  "ILS",
		67:  "INR",
		68:  "IQD",
		69:  "IRR",
		70:  "ISK",
		71:  "JMD",
		72:  "JOD",
		73:  "JPY",
		74:  "KES",
		75:  "KGS",
		76:  "KHR",
		77:  "KMF",
		78:  "KPW",
		79:  "KRW",
		80:  "KWD",
		81:  "KYD",
		82:  "KZT",
		83:  "LAK",
		84:  "LBP",
		85:  "LKR",
		86:  "LRD",
		87:  "LSL",
		88:  "LYD",
		89:  "MAD",
		90:  "MDL",
		91:  "MGA",
		92:  "MKD",
		93:  "MMK",
		94:  "MNT",
		95:  "MOP",
		96:  "MRU",
		97:  "MUR",
		98:  "MVR",
		99:  "MWK",
		100: "MXN",
		101: "MXV",
		102: "MYR",
		103: "MZN",
		104: "NAD",
		105: "NGN",
		106: "NIO",
		107: "NOK",
		108: "NPR",
		109: "NZD",
		110: "OMR",
		111: "PAB",
		112: "PEN",
		113: "PGK",
		114: "PHP",
		115: "PKR",
		116: "PLN",
		117: "PYG",
		118: "QAR",
		119: "RON",
		120: "RSD",
		121: "RUB",
		122: "RWF",
		123: "SAR",
		124: "SBD",
		125: "SCR",
		126: "SDG",
		127: "SEK",
		128: "SGD",
		129: "SHP",
		130: "SLL",
		131: "SOS",
		132: "SRD",
		133: "SSP",
		134: "STN",
		135: "SVC",
		136: "SYP",
		137: "SZL",
		138: "THB",
		139: "TJS",
		140: "TMT",
		141: "TND",
		142: "TOP",
		143: "TRY",
		144: "TTD",
		145: "TWD",
		146: "TZS",
		147: "UAH",
		148: "UGX",
		149: "USD",
		150: "USN",
		151: "UYI",
		152: "UYU",
		153: "UYW",
		154: "UZS",
		155: "VED",
		156: "VES",
		157: "VND",
		158: "VUV",
		159: "WST",
		160: "XAF",
		161: "XAG",
		162: "XAU",
		163: "XBA",
		164: "XBB",
		165: "XBC",
		166: "XBD",
		167: "XCD",
		168: "XDR",
		169: "XOF",
		170: "XPD",
		171: "XPF",
		172: "XPT",
		173: "XSU",
		174: "XTS",
		175: "XUA",
		176: "XXX",
		177: "YER",
		178: "ZAR",
		179: "ZMW",
		180: "ZWL",
	}
	Currency_value_short = map[string]int32{
		"UNSPECIFIED": 0,
		"AED":         1,
		"AFN":         2,
		"ALL":         3,
		"AMD":         4,
		"ANG":         5,
		"AOA":         6,
		"ARS":         7,
		"AUD":         8,
		"AWG":         9,
		"AZN":         10,
		"BAM":         11,
		"BBD":         12,
		"BDT":         13,
		"BGN":         14,
		"BHD":         15,
		"BIF":         16,
		"BMD":         17,
		"BND":         18,
		"BOB":         19,
		"BOV":         20,
		"BRL":         21,
		"BSD":         22,
		"BTN":         23,
		"BWP":         24,
		"BYN":         25,
		"BZD":         26,
		"CAD":         27,
		"CDF":         28,
		"CHE":         29,
		"CHF":         30,
		"CHW":         31,
		"CLF":         32,
		"CLP":         33,
		"CNY":         34,
		"COP":         35,
		"COU":         36,
		"CRC":         37,
		"CUC":         38,
		"CUP":         39,
		"CVE":         40,
		"CZK":         41,
		"DJF":         42,
		"DKK":         43,
		"DOP":         44,
		"DZD":         45,
		"EGP":         46,
		"ERN":         47,
		"ETB":         48,
		"EUR":         49,
		"FJD":         50,
		"FKP":         51,
		"GBP":         52,
		"GEL":         53,
		"GHS":         54,
		"GIP":         55,
		"GMD":         56,
		"GNF":         57,
		"GTQ":         58,
		"GYD":         59,
		"HKD":         60,
		"HNL":         61,
		"HRK":         62,
		"HTG":         63,
		"HUF":         64,
		"IDR":         65,
		"ILS":         66,
		"INR":         67,
		"IQD":         68,
		"IRR":         69,
		"ISK":         70,
		"JMD":         71,
		"JOD":         72,
		"JPY":         73,
		"KES":         74,
		"KGS":         75,
		"KHR":         76,
		"KMF":         77,
		"KPW":         78,
		"KRW":         79,
		"KWD":         80,
		"KYD":         81,
		"KZT":         82,
		"LAK":         83,
		"LBP":         84,
		"LKR":         85,
		"LRD":         86,
		"LSL":         87,
		"LYD":         88,
		"MAD":         89,
		"MDL":         90,
		"MGA":         91,
		"MKD":         92,
		"MMK":         93,
		"MNT":         94,
		"MOP":         95,
		"MRU":         96,
		"MUR":         97,
		"MVR":         98,
		"MWK":         99,
		"MXN":         100,
		"MXV":         101,
		"MYR":         102,
		"MZN":         103,
		"NAD":         104,
		"NGN":         105,
		"NIO":         106,
		"NOK":         107,
		"NPR":         108,
		"NZD":         109,
		"OMR":         110,
		"PAB":         111,
		"PEN":         112,
		"PGK":         113,
		"PHP":         114,
		"PKR":         115,
		"PLN":         116,
		"PYG":         117,
		"QAR":         118,
		"RON":         119,
		"RSD":         120,
		"RUB":         121,
		"RWF":         122,
		"SAR":         123,
		"SBD":         124,
		"SCR":         125,
		"SDG":         126,
		"SEK":         127,
		"SGD":         128,
		"SHP":         129,
		"SLL":         130,
		"SOS":         131,
		"SRD":         132,
		"SSP":         133,
		"STN":         134,
		"SVC":         135,
		"SYP":         136,
		"SZL":         137,
		"THB":         138,
		"TJS":         139,
		"TMT":         140,
		"TND":         141,
		"TOP":         142,
		"TRY":         143,
		"TTD":         144,
		"TWD":         145,
		"TZS":         146,
		"UAH":         147,
		"UGX":         148,
		"USD":         149,
		"USN":         150,
		"UYI":         151,
		"UYU":         152,
		"UYW":         153,
		"UZS":         154,
		"VED":         155,
		"VES":         156,
		"VND":         157,
		"VUV":         158,
		"WST":         159,
		"XAF":         160,
		"XAG":         161,
		"XAU":         162,
		"XBA":         163,
		"XBB":         164,
		"XBC":         165,
		"XBD":         166,
		"XCD":         167,
		"XDR":         168,
		"XOF":         169,
		"XPD":         170,
		"XPF":         171,
		"XPT":         172,
		"XSU":         173,
		"XTS":         174,
		"XUA":         175,
		"XXX":         176,
		"YER":         177,
		"ZAR":         178,
		"ZMW":         179,
		"ZWL":         180,
	}
	Currency_value_either = map[string]int32{
		"UNSPECIFIED":          0,
		"CURRENCY_UNSPECIFIED": 0,
		"AED":                  1,
		"CURRENCY_AED":         1,
		"AFN":                  2,
		"CURRENCY_AFN":         2,
		"ALL":                  3,
		"CURRENCY_ALL":         3,
		"AMD":                  4,
		"CURRENCY_AMD":         4,
		"ANG":                  5,
		"CURRENCY_ANG":         5,
		"AOA":                  6,
		"CURRENCY_AOA":         6,
		"ARS":                  7,
		"CURRENCY_ARS":         7,
		"AUD":                  8,
		"CURRENCY_AUD":         8,
		"AWG":                  9,
		"CURRENCY_AWG":         9,
		"AZN":                  10,
		"CURRENCY_AZN":         10,
		"BAM":                  11,
		"CURRENCY_BAM":         11,
		"BBD":                  12,
		"CURRENCY_BBD":         12,
		"BDT":                  13,
		"CURRENCY_BDT":         13,
		"BGN":                  14,
		"CURRENCY_BGN":         14,
		"BHD":                  15,
		"CURRENCY_BHD":         15,
		"BIF":                  16,
		"CURRENCY_BIF":         16,
		"BMD":                  17,
		"CURRENCY_BMD":         17,
		"BND":                  18,
		"CURRENCY_BND":         18,
		"BOB":                  19,
		"CURRENCY_BOB":         19,
		"BOV":                  20,
		"CURRENCY_BOV":         20,
		"BRL":                  21,
		"CURRENCY_BRL":         21,
		"BSD":                  22,
		"CURRENCY_BSD":         22,
		"BTN":                  23,
		"CURRENCY_BTN":         23,
		"BWP":                  24,
		"CURRENCY_BWP":         24,
		"BYN":                  25,
		"CURRENCY_BYN":         25,
		"BZD":                  26,
		"CURRENCY_BZD":         26,
		"CAD":                  27,
		"CURRENCY_CAD":         27,
		"CDF":                  28,
		"CURRENCY_CDF":         28,
		"CHE":                  29,
		"CURRENCY_CHE":         29,
		"CHF":                  30,
		"CURRENCY_CHF":         30,
		"CHW":                  31,
		"CURRENCY_CHW":         31,
		"CLF":                  32,
		"CURRENCY_CLF":         32,
		"CLP":                  33,
		"CURRENCY_CLP":         33,
		"CNY":                  34,
		"CURRENCY_CNY":         34,
		"COP":                  35,
		"CURRENCY_COP":         35,
		"COU":                  36,
		"CURRENCY_COU":         36,
		"CRC":                  37,
		"CURRENCY_CRC":         37,
		"CUC":                  38,
		"CURRENCY_CUC":         38,
		"CUP":                  39,
		"CURRENCY_CUP":         39,
		"CVE":                  40,
		"CURRENCY_CVE":         40,
		"CZK":                  41,
		"CURRENCY_CZK":         41,
		"DJF":                  42,
		"CURRENCY_DJF":         42,
		"DKK":                  43,
		"CURRENCY_DKK":         43,
		"DOP":                  44,
		"CURRENCY_DOP":         44,
		"DZD":                  45,
		"CURRENCY_DZD":         45,
		"EGP":                  46,
		"CURRENCY_EGP":         46,
		"ERN":                  47,
		"CURRENCY_ERN":         47,
		"ETB":                  48,
		"CURRENCY_ETB":         48,
		"EUR":                  49,
		"CURRENCY_EUR":         49,
		"FJD":                  50,
		"CURRENCY_FJD":         50,
		"FKP":                  51,
		"CURRENCY_FKP":         51,
		"GBP":                  52,
		"CURRENCY_GBP":         52,
		"GEL":                  53,
		"CURRENCY_GEL":         53,
		"GHS":                  54,
		"CURRENCY_GHS":         54,
		"GIP":                  55,
		"CURRENCY_GIP":         55,
		"GMD":                  56,
		"CURRENCY_GMD":         56,
		"GNF":                  57,
		"CURRENCY_GNF":         57,
		"GTQ":                  58,
		"CURRENCY_GTQ":         58,
		"GYD":                  59,
		"CURRENCY_GYD":         59,
		"HKD":                  60,
		"CURRENCY_HKD":         60,
		"HNL":                  61,
		"CURRENCY_HNL":         61,
		"HRK":                  62,
		"CURRENCY_HRK":         62,
		"HTG":                  63,
		"CURRENCY_HTG":         63,
		"HUF":                  64,
		"CURRENCY_HUF":         64,
		"IDR":                  65,
		"CURRENCY_IDR":         65,
		"ILS":                  66,
		"CURRENCY_ILS":         66,
		"INR":                  67,
		"CURRENCY_INR":         67,
		"IQD":                  68,
		"CURRENCY_IQD":         68,
		"IRR":                  69,
		"CURRENCY_IRR":         69,
		"ISK":                  70,
		"CURRENCY_ISK":         70,
		"JMD":                  71,
		"CURRENCY_JMD":         71,
		"JOD":                  72,
		"CURRENCY_JOD":         72,
		"JPY":                  73,
		"CURRENCY_JPY":         73,
		"KES":                  74,
		"CURRENCY_KES":         74,
		"KGS":                  75,
		"CURRENCY_KGS":         75,
		"KHR":                  76,
		"CURRENCY_KHR":         76,
		"KMF":                  77,
		"CURRENCY_KMF":         77,
		"KPW":                  78,
		"CURRENCY_KPW":         78,
		"KRW":                  79,
		"CURRENCY_KRW":         79,
		"KWD":                  80,
		"CURRENCY_KWD":         80,
		"KYD":                  81,
		"CURRENCY_KYD":         81,
		"KZT":                  82,
		"CURRENCY_KZT":         82,
		"LAK":                  83,
		"CURRENCY_LAK":         83,
		"LBP":                  84,
		"CURRENCY_LBP":         84,
		"LKR":                  85,
		"CURRENCY_LKR":         85,
		"LRD":                  86,
		"CURRENCY_LRD":         86,
		"LSL":                  87,
		"CURRENCY_LSL":         87,
		"LYD":                  88,
		"CURRENCY_LYD":         88,
		"MAD":                  89,
		"CURRENCY_MAD":         89,
		"MDL":                  90,
		"CURRENCY_MDL":         90,
		"MGA":                  91,
		"CURRENCY_MGA":         91,
		"MKD":                  92,
		"CURRENCY_MKD":         92,
		"MMK":                  93,
		"CURRENCY_MMK":         93,
		"MNT":                  94,
		"CURRENCY_MNT":         94,
		"MOP":                  95,
		"CURRENCY_MOP":         95,
		"MRU":                  96,
		"CURRENCY_MRU":         96,
		"MUR":                  97,
		"CURRENCY_MUR":         97,
		"MVR":                  98,
		"CURRENCY_MVR":         98,
		"MWK":                  99,
		"CURRENCY_MWK":         99,
		"MXN":                  100,
		"CURRENCY_MXN":         100,
		"MXV":                  101,
		"CURRENCY_MXV":         101,
		"MYR":                  102,
		"CURRENCY_MYR":         102,
		"MZN":                  103,
		"CURRENCY_MZN":         103,
		"NAD":                  104,
		"CURRENCY_NAD":         104,
		"NGN":                  105,
		"CURRENCY_NGN":         105,
		"NIO":                  106,
		"CURRENCY_NIO":         106,
		"NOK":                  107,
		"CURRENCY_NOK":         107,
		"NPR":                  108,
		"CURRENCY_NPR":         108,
		"NZD":                  109,
		"CURRENCY_NZD":         109,
		"OMR":                  110,
		"CURRENCY_OMR":         110,
		"PAB":                  111,
		"CURRENCY_PAB":         111,
		"PEN":                  112,
		"CURRENCY_PEN":         112,
		"PGK":                  113,
		"CURRENCY_PGK":         113,
		"PHP":                  114,
		"CURRENCY_PHP":         114,
		"PKR":                  115,
		"CURRENCY_PKR":         115,
		"PLN":                  116,
		"CURRENCY_PLN":         116,
		"PYG":                  117,
		"CURRENCY_PYG":         117,
		"QAR":                  118,
		"CURRENCY_QAR":         118,
		"RON":                  119,
		"CURRENCY_RON":         119,
		"RSD":                  120,
		"CURRENCY_RSD":         120,
		"RUB":                  121,
		"CURRENCY_RUB":         121,
		"RWF":                  122,
		"CURRENCY_RWF":         122,
		"SAR":                  123,
		"CURRENCY_SAR":         123,
		"SBD":                  124,
		"CURRENCY_SBD":         124,
		"SCR":                  125,
		"CURRENCY_SCR":         125,
		"SDG":                  126,
		"CURRENCY_SDG":         126,
		"SEK":                  127,
		"CURRENCY_SEK":         127,
		"SGD":                  128,
		"CURRENCY_SGD":         128,
		"SHP":                  129,
		"CURRENCY_SHP":         129,
		"SLL":                  130,
		"CURRENCY_SLL":         130,
		"SOS":                  131,
		"CURRENCY_SOS":         131,
		"SRD":                  132,
		"CURRENCY_SRD":         132,
		"SSP":                  133,
		"CURRENCY_SSP":         133,
		"STN":                  134,
		"CURRENCY_STN":         134,
		"SVC":                  135,
		"CURRENCY_SVC":         135,
		"SYP":                  136,
		"CURRENCY_SYP":         136,
		"SZL":                  137,
		"CURRENCY_SZL":         137,
		"THB":                  138,
		"CURRENCY_THB":         138,
		"TJS":                  139,
		"CURRENCY_TJS":         139,
		"TMT":                  140,
		"CURRENCY_TMT":         140,
		"TND":                  141,
		"CURRENCY_TND":         141,
		"TOP":                  142,
		"CURRENCY_TOP":         142,
		"TRY":                  143,
		"CURRENCY_TRY":         143,
		"TTD":                  144,
		"CURRENCY_TTD":         144,
		"TWD":                  145,
		"CURRENCY_TWD":         145,
		"TZS":                  146,
		"CURRENCY_TZS":         146,
		"UAH":                  147,
		"CURRENCY_UAH":         147,
		"UGX":                  148,
		"CURRENCY_UGX":         148,
		"USD":                  149,
		"CURRENCY_USD":         149,
		"USN":                  150,
		"CURRENCY_USN":         150,
		"UYI":                  151,
		"CURRENCY_UYI":         151,
		"UYU":                  152,
		"CURRENCY_UYU":         152,
		"UYW":                  153,
		"CURRENCY_UYW":         153,
		"UZS":                  154,
		"CURRENCY_UZS":         154,
		"VED":                  155,
		"CURRENCY_VED":         155,
		"VES":                  156,
		"CURRENCY_VES":         156,
		"VND":                  157,
		"CURRENCY_VND":         157,
		"VUV":                  158,
		"CURRENCY_VUV":         158,
		"WST":                  159,
		"CURRENCY_WST":         159,
		"XAF":                  160,
		"CURRENCY_XAF":         160,
		"XAG":                  161,
		"CURRENCY_XAG":         161,
		"XAU":                  162,
		"CURRENCY_XAU":         162,
		"XBA":                  163,
		"CURRENCY_XBA":         163,
		"XBB":                  164,
		"CURRENCY_XBB":         164,
		"XBC":                  165,
		"CURRENCY_XBC":         165,
		"XBD":                  166,
		"CURRENCY_XBD":         166,
		"XCD":                  167,
		"CURRENCY_XCD":         167,
		"XDR":                  168,
		"CURRENCY_XDR":         168,
		"XOF":                  169,
		"CURRENCY_XOF":         169,
		"XPD":                  170,
		"CURRENCY_XPD":         170,
		"XPF":                  171,
		"CURRENCY_XPF":         171,
		"XPT":                  172,
		"CURRENCY_XPT":         172,
		"XSU":                  173,
		"CURRENCY_XSU":         173,
		"XTS":                  174,
		"CURRENCY_XTS":         174,
		"XUA":                  175,
		"CURRENCY_XUA":         175,
		"XXX":                  176,
		"CURRENCY_XXX":         176,
		"YER":                  177,
		"CURRENCY_YER":         177,
		"ZAR":                  178,
		"CURRENCY_ZAR":         178,
		"ZMW":                  179,
		"CURRENCY_ZMW":         179,
		"ZWL":                  180,
		"CURRENCY_ZWL":         180,
	}
)

// ShortString returns the un-prefixed string representation of the enum value
func (x Currency) ShortString() string {
	return Currency_name_short[int32(x)]
}
func (x Currency) Value() (driver.Value, error) {
	return []uint8(x.ShortString()), nil
}
func (x *Currency) Scan(value interface{}) error {
	var strVal string
	switch vt := value.(type) {
	case []uint8:
		strVal = string(vt)
	case string:
		strVal = vt
	default:
		return fmt.Errorf("invalid type %T", value)
	}
	val := Currency_value_either[strVal]
	*x = Currency(val)
	return nil
}
